/*isMeber = true;
console.log ("la cuota es de : " + (isMeber ? "$2:00" : "$10.00"));

cliente =true;
importe=6000;
formaPago="efectivo";
//sin operador logico

if(cliente===true){
    if(importe>5000){
        if(formaPago==="efectivo"){
            console.log ("tiene descuento");
        }else{
            console.log ("necesitas pagar en efectivo");
        }
    }else{
        console.log ("necesitas un importe mayor a $5000");
    }
}else {
    console.log ("necesitas ser cliente");
}
//con operadores logicos 
if (cliente==true && importe > 5000 && formaPago=="efectivo"){
    console.log ("TIENE DESCUENTO");

}else{
    console.log ("no tienes descuento");
}

//AND
function And (num){
    
        if( num > 10  && num  % 2 === 0 ) console.log(true);
        else console.log(false);
    };
    And (11);
    And (12); 

    // OR
function operadorOr(str) {
    if (str === 'Henry' || str.length < 2) console.log(true);
    else console.log(false);
 }
 operadorOr('Henry');
 operadorOr('Javascript');
 operadorOr('H');

 // NOT
function negacion(permiso) {
permiso ? console.log('Tiene permiso'): console.log ("no tiene permiso");
 }
 negacion(true);
 negacion(false);*/
/*
//siglos en js
for(let x=1; x<100; x++){
console.log (x + );
}*/
/*
for (let x=1; x<11; x++){
    console.log ("2 x "+ x + "=" + x *2 );
}*/
/*
function tabladel(num){
    for (let x=1; x<11; x++){
        console.log (num +" x "+ x + "=" + x *num );
} }
tabladel(856);*/
/*
for (let x=1; x!==11;x++ ){
    for(let y=1; y!==11; y++){
        console.log (x + " x "+ y +" = "+ x * y );
    }
}*/
/*
function tablasDelAl (num1,num2){
    for (let x=num1; x!==num2 + 1; x++){
        for(let y=1; y!==11; y++){
            console.log (x + " x "+ y +" = "+ x * y );
    }
}}
tablasDelAl(6,12); 
*/

